name: Sync Hotspots
on:
  schedule:
    - cron: "0 */2 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Hotspots
        run: |
          response=$(curl --write-out %{http_code} --silent --output /dev/null --request POST \
          --url 'https://birdinghotspots.org/api/hotspot/sync?key=${{ secrets.CRON_KEY }}')
          if [ $response -eq 200 ]; then
            echo "Request was successful (Status Code: $response)"
          else
            echo "Request failed with Status Code: $response"
            exit 1
          fi
